version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/home/static
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build:
      context: src/.
      dockerfile: src/Dockerfile
    depends_on:
      - redis
      - elasticsearch
    env_file:
      - src/dev.env

  tests:
    build:
      context: tests/.
      dockerfile: tests/Dockerfile
    depends_on:
      - redis
      - elasticsearch
      - api

  etl:
    build:
      context: postgres_to_es/.
      dockerfile: src/Dockerfile
    env_file:
      - postgres_to_es/dev.env
    environment:
      PG_HOST: db
      REDIS_HOST: redis
      ES_HOST: elasticsearch
    depends_on:
      - db
      - elasticsearch
      - redis
    command: bash -c "/usr/local/bin/python3 ETL.py"

  db:
    image: postgres:13
    container_name: postgresql_13
    environment:
      POSTGRES_USER: movies_admin
      POSTGRES_DB: movies_admin
      POSTGRES_PASSWORD: docker
    volumes:
      - /srv/db.data:/var/lib/postgresql/data
      - ./movies_admin/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  es_data:
  redis_data: